### PR TITLE
Fix EasyUnlock

### PR DESCRIPTION
**Pull request by turicfr**
* Change the index of the `matched` parameter in `onPasswordChecked` hook to 1. Previously it referred to `timeoutMs` which caused a `ClassCastException`.

In order to match `onPasswordChecked`:
* Swap the first two parameters of `dismiss`.
* Call to `reportUnlockAttempt`.

### CODE REVIEW

**Comment by siavash79** [comment]
Thanks for the PR

Can you please let me know the reason this PR exists? I mean easy unlock was not working on your device? What's your device and rom? Because as far as I know it was working fine on supported roms.

Cheers

**Comment by turicfr** [comment]
Yes, easy unlock was not working on my device (Pixel 3 with PixelExperience 13.0-20230424).

The reason of this PR is to be aligned with the main Android codebase. Here's the signature of [`onPasswordChecked`](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/packages/SystemUI/src/com/android/keyguard/KeyguardAbsKeyInputViewController.java;bpv=1;bpt=1;l=171?gsn=onPasswordChecked&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%2Fmain%2F%2Fmain%3Flang%3Djava%3Fpath%3Dcom.android.keyguard.KeyguardAbsKeyInputViewController%238c6149a04853868714bd593693139c024ed83e7172d65da28887c7d45f2cbd0e) from cs.android.com:
```
void onPasswordChecked(int userId, boolean matched, int timeoutMs, boolean isValidPassword)
```
This shows that we actually want to get the 2nd parameter, and not the 3rd as it is now. This function also calls to `reportUnlockAttempt`, which seems mandatory in this case.

Also, I had to pass `securityVerified` before `targetUserId` to [`dismiss`](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/packages/SystemUI/src/com/android/keyguard/KeyguardSecurityCallback.java;drc=5eb93a52e1498d7ad2bd23373f4df1e61b635700;bpv=1;bpt=1;l=28?gsn=dismiss&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%2Fmain%2F%2Fmain%3Flang%3Djava%3Fpath%3Dcom.android.keyguard.KeyguardSecurityCallback%23a5b03ca577cd8444d23d99c4c286ca99e0c8dd76034800bebc557e8f0d3f27a9). It has actually never been this way in the codebase.

I guess these inconsistencies came from roms that actually fiddled with this. I'm new here, so this change may be wrong.

**Comment by siavash79** [comment]
I see. Can you please confirm that you've made an internal build base on this change and it actually fixes your issue?

About the PR:
Well AOSPMods main target is based on Pixel phone. As of now, easy unlock works on Pixel phones as intended. I do understand that it might be even different from main AOSP code.
So in such cases (to add compatibility with PE), we need to find a way to incorporate BOTH ways in the case, so that we don't break compatibility with Pixels

**Comment by siavash79** [comment]
My internal build breaks it for Pixel rom:

`Crash unexpectedly: java.lang.NoSuchMethodError: com.android.keyguard.KeyguardSecurityContainerController$2#reportUnlockAttempt(java.lang.Integer,java.lang.Boolean,java.lang.Integer)
                 	at X.hwWSqXoQP.loY.kw.WSQ.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
                 	at X.hwWSqXoQP.loY.kw.WSQ.XposedHelpers.f(Unknown Source:0)
                 	at X.hwWSqXoQP.loY.kw.WSQ.c.get(Unknown Source:8)
                 	at java.util.Optional.orElseThrow(Optional.java:404)
                 	at X.hwWSqXoQP.loY.kw.WSQ.XposedHelpers.findMethodBestMatch(SourceFile:1)
                 	at X.hwWSqXoQP.loY.kw.WSQ.XposedHelpers.findMethodBestMatch(SourceFile:3)
                 	at X.hwWSqXoQP.loY.kw.WSQ.XposedHelpers.callMethod(SourceFile:2)
                 	at sh.siava.AOSPMods.modpacks.systemui.EasyUnlock$2.lambda$afterHookedMethod$0(EasyUnlock.java:95)
                 	at sh.siava.AOSPMods.modpacks.systemui.EasyUnlock$2$$ExternalSyntheticLambda0.run(Unknown Source:4)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

**Comment by siavash79** [comment]
So if you can confirm your internal build for PE, then we can find a way to merge both ways together

**Comment by turicfr** [comment]
Yes, I can confirm it works on my PE rom. However, I think it needs some more testing, as it is a sensitive code.

**Comment by siavash79** [comment]
Since we're not concentrating on AOSP anymore, I'll have to close this PR

**Comment by Pxdsey** [comment]
@turicfr Can you help me with something you've previously created? anywhere I can contact? thanks.

**Comment by EleoXDA** [comment]
You can write in telegram support group. It is written in ReadMe

**Pull request closed without merging**
