### PR TITLE
Update arrays.xml

### PR DESCRIPTION
**Pull request by trinhloivn**
add options for Vietnamese

### CODE REVIEW

**Comment by siavash79** [comment]
Thanks! I'll keep it unmerged for now, until strings.xml is also added. Then we'll keep them together

**Comment by trinhloivn** [comment]
> 

oh ok
but i think strings.xml(vietnamese) added 
https://github.com/siavash79/AOSPMods/tree/stable/app/src/main/res/values-vi
sorry if it not good
thank u

**Comment by EleoXDA** [comment]
Strings.xml was added to stable version, not for canary

**Comment by EleoXDA** [comment]
We firstly push to canary version (default branch) and after, to stable version

**Comment by siavash79** [comment]
Ok now I'm confused

Vietnamese strings when and how is added to stable?

**Comment by siavash79** [comment]
Ok I deleted the stings from stable branch

Please never EVER merge anything into stable. It will mess its sync with canary and is a huge (huge, huge) headache to fix

Please make a new pull request for canary

**Comment by trinhloivn** [comment]
> Ok I deleted the stings from stable branch
> 
> Please never EVER merge anything into stable. It will mess its sync with canary and is a huge (huge, huge) headache to fix
> 
> Please make a new pull request for canary

Oh ok,sorry for that. I dont know...
i will try again

**Comment by EleoXDA** [comment]
> Ok now I'm confused
> 
> Vietnamese strings when and how is added to stable?

That would be my mistake. I checked the strings and they were fine. Didn't notice that they weren't addressed to default branch, but stable one. Was going to talk to you about it...forgot

**Pull request closed without merging**
