### PR TITLE
TRstrings.xml

### PR DESCRIPTION
**Pull request by TeaqariaWTF**
Turkish language

### CODE REVIEW

**Comment by siavash79** [comment]
Thank you very much for your contribution.

**HOWEVER**: you've made your changes in the main strings file, effectively damaging the English translation!

you must put the strings.xml file in the directory "values-tr" (like other languages: values-ro, values-ru, valued-de,.....)

Since I don't have access to your forked repository, please move the file to the correct location and make a new pull request

**Review by siavash79 — CHANGES_REQUESTED** [review]
Please move it to values-tr directory

**Comment by siavash79** [comment]
Plus: after you moved the file to the correct location, please re-copy the original strings.xml from the main repository

**Comment by TeaqariaWTF** [comment]
sorry for the mistake, i submitted a new pull request hope i got it right this time

**Pull request closed without merging**
